spring.application.name=security
# Thông tin k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=23102006

# C?u hình Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
